
# Команда, используемая для рандомной телепортации
rtpCommand: "rtp"

# Минимальный онлайн, который должен быть на сервере, чтобы работала телепортация с типом NEARBY_PLAYERS (рядом с игроками)
nearbyPlayersMinOnline: 3

# Здесь можно настроить несколько каналов телепортации
channels:
  # Название канала. Используется в разрешении на его использование. rtp.channel.normal
  normal:
    # Обязательный параметр. Аргумент этого канала. Можно использовать так - /<команда> <аргумент> (Например: rtp safe)
    argument: "safe"

    # Обязательный параметр. Тип канала. Может быть DEFAULT и NEARBY_PLAYERS. DEFAULT - Обычное ртп. NEARBY_PLAYERS - Рядом с игроками
    type: DEFAULT

    # Необязательный параметр. Указывайте, если хотите использовать по умолчанию, если игрок не укажет никакой аргумент. (Например: rtp)
    default: true

    # Необязательный параметр. Задержка на использование телепортации в текущем канале (в секундах)
    cooldown: 15

    # Обязательный параметр. Радиус телепортации. Не работает при типе NEARBY_PLAYERS. Нужно указать x и z. Форматирование: <от...> ! <до...>
    range:
      x: -1000 ! 1000
      z: -1000 ! 1000

    # Необязательный параметр. Тип телепортации. Может быть NORMAL и SKY. При NORMAL вас телепортирует на землю. При SKY вас телепортирует в воздух
    # Как на гриферских серверах. По умолчанию - SKY
    teleportType: SKY

    # Необязательный параметр. Блоки, на которые плагин не будет телепортировать в текущем канале.
    blacklistedBlocks:
      - "lava"
      - "stationary_lava"

    # Необязательный параметр. При телепортации будет сниматься голод. Всего 20 единиц голода.
    hunger: 4

    # Необязательный параметр. Действия при рандомной телепортации в этом канале. 1 сек = 20 тиков
    # Список действий:
    # effect, <тип> <длительность (в тиках)> <уровень> && ... - выдать эффекты игроку.
    # title, <Заголовок> && <Подзаголовок> - отправить тайтл игроку.
    actions:
      - "effect, water_breathing 200 1 && fire_resistance 200 1"
      - "title, &4Рандомная телепортация && &fВы были телепортированы на координаты &a{x} {y} {z}"

  far:
    argument: "far"
    type: DEFAULT
    range:
      x: -3000 ! 2000
      z: -5000 ! 4000
    teleportType: NORMAL
    hunger: 8
    actions:
      - "effect, water_breathing 200 1 && fire_resistance 200 1"
      - "title, &4Далёкая телепортация && &fВы были телепортированы на координаты &a{x} {y} {z}"
  nearby:
    argument: "near"
    type: NEARBY_PLAYERS
    teleportType: NORMAL

    # Обязательный параметр. Радиус телепортации рядом с игроками.
    # В указанном диапазоне игрок будет телепортирован относительно рандомного игрока на сервере.
    # Форматирование: <от...> ! <до...>
    nearbyRange: 10 ! 100

    cooldown: 40
    hunger: 8
    actions:
      - "title, &4Телепортация рядом с игроками && &fВы были телепортированы недалеко от игрока &a{player}"

